name: issue-slack-notification
on:
 issues:
   types: [opened]

jobs: 
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: chmod
        run: chmod +x notify.sh

      - name: send slack notification
        run: ./notify.sh "${{ github.event.issue.title }}"
